<?php
// Portal API configuration. Edit here if your host needs different paths.
// Everything else in api/ reads from these constants.

// Folder that holds index.html (one level above api/).
define('PORTAL_ROOT', dirname(__DIR__));

// Where the SQLite database and temporary upload chunks live.
// Must be writable by PHP. It ships with an .htaccess that blocks web access;
// on nginx hosts, deny /data/ in the server config instead.
define('DATA_DIR', PORTAL_ROOT . '/data');
define('DB_FILE', DATA_DIR . '/portal.sqlite');
define('TMP_DIR', DATA_DIR . '/tmp');

// Generated by tools/build-course-manifest.mjs — the list of courses, videos and original quizzes.
define('MANIFEST_FILE', DATA_DIR . '/course-manifest.json');

// Admin-uploaded replacement videos are written here (web-served).
define('UPLOADS_DIR', PORTAL_ROOT . '/uploads');
define('CUSTOM_UPLOADS_SUBDIR', 'custom');

// Sessions
define('SESSION_NAME', 'dhportal');
define('SESSION_LIFETIME', 60 * 60 * 12); // 12 hours of inactivity

// Uploads: videos are sent in chunks so shared-host post limits don't matter.
define('CHUNK_SIZE', 1024 * 1024);            // 1 MB per request
define('MAX_VIDEO_BYTES', 1024 * 1024 * 1024); // 1 GB per video

// Passwords
define('MIN_PASSWORD_LENGTH', 8);

// Login throttling: after this many failures for an email/IP within the window, wait.
define('LOGIN_MAX_FAILURES', 10);
define('LOGIN_WINDOW_SECONDS', 15 * 60);

// The very first run creates this super admin (forced to change the password on first login).
define('SEED_SUPERADMIN_EMAIL', 'scott@44interactive.com');
define('SEED_SUPERADMIN_PASSWORD', '44i123');
define('SEED_SUPERADMIN_FIRST', 'Scott');
define('SEED_SUPERADMIN_LAST', '');
define('SEED_SUPERADMIN_GROUP', '44 Interactive');

// "Sign in as" (impersonation) is a super-admin feature. Leave this list non-empty to
// restrict it to specific super admin accounts; an empty array allows every super admin.
define('IMPERSONATE_ALLOWED_EMAILS', ['scott@44interactive.com']);

// Set true temporarily to include exception messages in API error responses.
define('DEBUG', false);
